# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: CI_Tailwind_Webapp

  jobs:
  - job: Build_Webapp

    steps:
    - task: Npm@1
      displayName: Install dependencies in client app 
      inputs:
        command: 'install'
        workingDir: 'Source/Tailwind.Traders.Web/ClientApp'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration Release'
        workingDirectory: 'Source/Tailwind.Traders.Web'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        arguments: '-c Release -o publish'
        zipAfterPublish: false
        modifyOutputPath: false
        workingDirectory: 'Source/Tailwind.Traders.Web'

- stage: CD_Tailwind_Webapp

  jobs:
  - job: Deploy_Webapp

    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'ARM-TailWindRG'
        appType: 'webApp'
        WebAppName: 'tt-webside'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'